quarkus.application.name=user-auth-service
quarkus.http.port=8081

# Datasource
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=postgres
quarkus.datasource.password=postgres
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/User

# Hibernate ORM
# Use 'update' for dev only
quarkus.hibernate-orm.database.generation=update
quarkus.hibernate-orm.log.sql=true
quarkus.hibernate-orm.dialect=org.hibernate.dialect.PostgreSQLDialect

# Connection Pool
quarkus.datasource.jdbc.min-size=5
quarkus.datasource.jdbc.max-size=10

# Dev convenience
quarkus.log.category."org.hibernate.SQL".level=DEBUG
quarkus.log.category."org.hibernate.orm.jdbc.bind".level=TRACE

# Enable JWT
quarkus.smallrye-jwt.enabled=true

# Issuer must match token creation
mp.jwt.verify.issuer=bank-auth-service

# Where roles are stored in JWT
quarkus.smallrye-jwt.roles-claim=groups

# JWT signing
smallrye.jwt.sign.key.location=privateKey.pem

# JWT validation (even auth service should validate)
mp.jwt.verify.publickey.location=publicKey.pem

# Force JWT auth globally
quarkus.http.auth.proactive=true
