spring.application.name=transaction

server.port=8083

# PostgreSQL JDBC Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/Transaction
spring.datasource.username=postgres
spring.datasource.password=postgres

# JPA / Hibernate
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

spring.security.oauth2.resourceserver.jwt.public-key-location=classpath:publicKey.pem

resilience4j.circuitbreaker.instances.accountService.slidingWindowSize=10
resilience4j.circuitbreaker.instances.accountService.minimumNumberOfCalls=5
resilience4j.circuitbreaker.instances.accountService.failureRateThreshold=50
resilience4j.circuitbreaker.instances.accountService.waitDurationInOpenState=10s
resilience4j.circuitbreaker.instances.accountService.permittedNumberOfCallsInHalfOpenState=3

resilience4j.retry.instances.accountService.maxAttempts=3
resilience4j.retry.instances.accountService.waitDuration=500ms

services.account.url=http://localhost:8082


spring.security.oauth2.client.registration.transaction-client.provider=auth-server
spring.security.oauth2.client.registration.transaction-client.client-id=transaction-service
spring.security.oauth2.client.registration.transaction-client.client-secret=transaction-secret
spring.security.oauth2.client.registration.transaction-client.authorization-grant-type=client_credentials
spring.security.oauth2.client.registration.transaction-client.scope=internal

spring.security.oauth2.client.provider.auth-server.token-uri=http://localhost:9000/oauth2/token

logging.level.org.springframework.security=DEBUG